#!/bin/bash

MAX_BRIGHTNESS=$(cat /sys/class/backlight/intel_backlight/max_brightness)
CUR_BRIGHTNESS=$(cat /sys/class/backlight/intel_backlight/brightness)
PERCENT_BRIGHTNESS=$(ruby -e "print '%d' % [100*($CUR_BRIGHTNESS/$MAX_BRIGHTNESS.0)]")
echo " $PERCENT_BRIGHTNESS%"
