#!/bin/bash

amixer_status=$(amixer sget Master)
right_speaker=$(echo $amixer_status | grep 'Right:')
volume=$(echo $right_speaker | awk -F '[][]' '{ print $2 }')
powered=$(echo $right_speaker | awk -F '[][]' '{ print $4 }')

#vol=$(amixer sget Master | grep 'Right:' | awk -F '[][]' '{print $2}')
volume=${volume::-1}


if [[ "$powered" == "off" ]]; then
  volume="   $volume%"
elif [[ volume -eq "0" ]]; then
  volume="   $volume%"
elif (( volume < "0")); then
  volume="   $volume%"
elif (( volume <= "50")); then
  volume=" $volume%"
else
  volume=" $volume%"
fi

echo $volume
