#!/bin/bash

{
  location_csv=`curl --silent freegeoip.net/csv/ | cut -d ',' -f6,9,10`
  location_data=(`echo $location_csv | sed 's/,/\n/g'`)
  location=${location_data[0]}
  lat=${location_data[1]}
  lng=${location_data[2]}
  
  weather_url="https://api.darksky.net/forecast/2cf3878b8080ab15e427d51e9c094bd6/$lat,$lng?exclude=minutely,hourly,flags&units=ca"
  weather_result=$(curl --silent $weather_url)
  
  icon=$(echo $weather_result | jq -r '.currently.icon')
  cur_temp_raw=$(echo $weather_result | jq -r '.currently.temperature')
  
  daily=$(echo $weather_result | jq -r '.daily.data[0]')
  min_temp_raw=$(echo $daily | jq -r '.temperatureMin')
  max_temp_raw=$(echo $daily | jq -r '.temperatureMax')
  
  min_temp=$(echo "($min_temp_raw+0.5)/1" | bc)
  cur_temp=$(echo "($cur_temp_raw+0.5)/1" | bc)
  max_temp=$(echo "($max_temp_raw+0.5)/1" | bc)
  
  case $icon in
    clear*)
      icon=$1
      ;;
    rain)
      icon=
      ;;
    snow)
      icon=$1
      ;;
    sleet)
      icon=$1
      ;;
    wind)
      icon=$1
      ;;
    fog)
      icon=$1
      ;;
    cloudy)
      icon=
      ;;
    partly-cloudy*)
      icon=
      ;;
    *)
      icon=$1
      ;;
  esac
  
  echo "$location $icon ( $min_temp  $cur_temp  $max_temp) C"
} || {
  echo ""
}
