#!/bin/bash

DARK_SKY_KEY="2cf3878b8080ab15e427d51e9c094bd6"

function get_location() {
  location_json=$(curl --silent freegeoip.net/json/)
  location=$(echo $location_json | jq -r '.city')
  lat=$(echo $location_json | jq -r '.latitude')
  lng=$(echo $location_json | jq -r '.longitude')
}

function get_weather() {
  weather_url="https://api.darksky.net/forecast/$DARK_SKY_KEY/$lat,$lng?exclude=minutely,hourly,flags&units=ca"
  weather_result=$(curl --silent $weather_url)
  
  icon=$(echo $weather_result | jq -r '.currently.icon')
  cur_temp_raw=$(echo $weather_result | jq -r '.currently.temperature')
  
  daily=$(echo $weather_result | jq -r '.daily.data[0]')
  min_temp_raw=$(echo $daily | jq -r '.temperatureMin')
  max_temp_raw=$(echo $daily | jq -r '.temperatureMax')
  
  min_temp=$(echo "($min_temp_raw+0.5)/1" | bc)
  cur_temp=$(echo "($cur_temp_raw+0.5)/1" | bc)
  max_temp=$(echo "($max_temp_raw+0.5)/1" | bc)
  
  case $icon in
    clear*)
      icon=
      ;;
    rain)
      icon=
      ;;
    snow)
      icon=
      ;;
    sleet)
      icon=
      ;;
    wind)
      icon="wind"
      ;;
    fog)
      icon="fog"
      ;;
    cloudy)
      icon=
      ;;
    partly-cloudy*)
      icon=
      ;;
    *)
      icon=$icon
      ;;
  esac
}

action=$1

get_location
get_weather

case $action in
  all)
    echo "$location $icon [$min_temp|$cur_temp|$max_temp]°C"
    ;;
  summary)
    echo "$location $icon $cur_temp°C"
    ;;
  debug)
    echo $location_json
    echo $location
    echo $weather_url
    echo $weather_result
    ;;
  *)
    ;;
esac

