#!/bin/bash

USER_HOME="/home/quinnjn"
GIT_LOCATION="$USER_HOME/git/github.com/quinnjn/dotfiles"
FILE=$1
FILE_TO_EDIT=$GIT_LOCATION/$FILE

set -e
set -u
set -o pipefail

if [ -z "$FILE" ]; then
  echo "Requires a file to edit"
  exit -1
fi

vim $FILE_TO_EDIT
git add $FILE_TO_EDIT
git commit -v
cp $FILE_TO_EDIT $USER_HOME
source ~/.bashrc
