#!/bin/bash

USER_HOME="/home/quinnjn"
GIT_LOCATION="$USER_HOME/git/github.com/quinnjn/dotfiles"
FILE=$1

set -e
set -u
set -o pipefail

if [ -z "$FILE" ]; then
  echo "Requires a file to edit"
  exit -1
fi

vim $GIT_LOCATION/$FILE
cp $GIT_LOCATION/$FILE $USER_HOME
source ~/.bashrc
